
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CHAR COMMA DOUBLE FLOAT ID INT SEMICOLONstatements : type declaration_list SEMICOLON\n                  | type declaration_list COMMA declaration_list SEMICOLONtype : INT\n            | FLOAT\n            | CHAR\n            | DOUBLEdeclaration_list : ID\n                       | declaration_list COMMA ID'
    
_lr_action_items = {'INT':([0,],[3,]),'FLOAT':([0,],[4,]),'CHAR':([0,],[5,]),'DOUBLE':([0,],[6,]),'$end':([1,9,14,],[0,-1,-2,]),'ID':([2,3,4,5,6,10,13,],[8,-3,-4,-5,-6,12,15,]),'SEMICOLON':([7,8,11,12,15,],[9,-7,14,-7,-8,]),'COMMA':([7,8,11,12,15,],[10,-7,13,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statements':([0,],[1,]),'type':([0,],[2,]),'declaration_list':([2,10,],[7,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statements","S'",1,None,None,None),
  ('statements -> type declaration_list SEMICOLON','statements',3,'p_statements','var_declaration.py',38),
  ('statements -> type declaration_list COMMA declaration_list SEMICOLON','statements',5,'p_statements','var_declaration.py',39),
  ('type -> INT','type',1,'p_type','var_declaration.py',43),
  ('type -> FLOAT','type',1,'p_type','var_declaration.py',44),
  ('type -> CHAR','type',1,'p_type','var_declaration.py',45),
  ('type -> DOUBLE','type',1,'p_type','var_declaration.py',46),
  ('declaration_list -> ID','declaration_list',1,'p_declaration_list','var_declaration.py',49),
  ('declaration_list -> declaration_list COMMA ID','declaration_list',3,'p_declaration_list','var_declaration.py',50),
]
